### ISSUE TITLE
unsafe mutable pointers

### ISSUE THREAD

**Issue by kallipigous** [n6xej/StructureCloudScanner#1]
I'm getting 6 compilation errors when I try to compile this on swift 3.0 ios 10

 Cannot convert value of type 'UnsafePointer<_>' to expected argument type 'UnsafeMutableRawPointer!'

Any thoughts?

**Comment by n6xej** [comment]
As much as I love the language I hate the way Swift does pointers and it seems like every release they change it.  On Xcode 8.1 where you are getting the errors change withUnsafePointer to withUnsafeMutablePointer.

**Comment by kallipigous** [comment]
Hi in viewcontroller+OpenGL

I’ve fixed (I think) 3 three of them by converting but what’s left is  three instances of

withUnsafePointer(to: &colorCameraPoseInDepthCoordinateSpace, {
                    $0.withMemoryRebound(to: Float.self, capacity: 16, {
                        depthFrame.colorCameraPose(inDepthCoordinateFrame: $0)

```
                })
            })
```

it’s the depthframe.colorCameraPose it doesn't like

I commented them out and it compiled and worked but I got no bounding cube showing.

I don't think that’s the same issue though

**Comment by n6xej** [comment]
I just checked in the fix, there were a total of 6 of them to change

**Comment by kallipigous** [comment]
magic yes I fixed three but I’ll grab it now many thanks

**Comment by n6xej** [comment]
Thanks for letting me know.

**Comment by kallipigous** [comment]
Works great and the bounding box is back. Many thanks will study.
